### ISSUE TITLE
GHC compilation error: Simplifier ticks exhausted

### ISSUE THREAD

**Issue by cpichard** [ekmett/openexr#1]
Hi,

When compiling the bindings on my configuration 
- https://github.com/cpichard/openexr/tree/develop
- openSUSE 12.1 (x86_64)
- ghc 7.8.2

I get the following error:

```
Preprocessing library OpenEXR-0.1...
[1 of 2] Compiling Graphics.OpenEXR.Half ( dist/build/Graphics/OpenEXR/Half.hs, dist/build/Graphics/OpenEXR/Half.o )

==================== FloatOut stats: ====================
69 Lets floated to top level; 0 Lets floated elsewhere; from 53 Lambda groups


==================== FloatOut stats: ====================
2 Lets floated to top level; 0 Lets floated elsewhere; from 103 Lambda groups


<no location info>:
    ghc: panic! (the 'impossible' happened)
  (GHC version 7.8.2 for x86_64-unknown-linux):
        Simplifier ticks exhausted
    When trying UnfoldingDone lvl_s40W{v} [lid]
    To increase the limit, use -fsimpl-tick-factor=N (default 100)
    If you need to do this, let GHC HQ know, and what factor you needed
    Total ticks:     109400

    109400 UnfoldingDone
      109399 lvl_s40W{v} [lid]
      1 OpenEXR-0.1:Graphics.OpenEXR.Half.$WHALF_EPSILON{v r3qx} [gid]

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug. 
```

It seems related to this ghc issue: https://ghc.haskell.org/trac/ghc/ticket/5539. I don't know what the simplifier ticks is supposed to do, but raising the value as suggested in the message doesn't solve the issue, it just takes more time before the crash:

```
cabal build --ghc-option=-fsimpl-tick-factor=109400
...
   ghc: panic! (the 'impossible' happened)
...
   Total ticks:     119683600
...
    119683600 UnfoldingDone
```

Cyril

**Comment by ekmett** [comment]
This appears to have been an old bug in the GHC simplifier, which was triggered by a high amount of inlining. 7.8 was a pretty bad era in GHC's inliner performance.

Perhaps I should switch from INLINE to INLINABLE to help compile speed and end-run around this on old GHCs.

**Comment by ekmett** [comment]
There is no use of inline left in this library, so any further errors are on someone else. =)

**Comment by cpichard** [comment]
Thanks !
